# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market_data.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11market_data.proto\"\x93\x01\n\x06Quotes\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\x12\x14\n\x0creceive_time\x18\x03 \x01(\x03\x12\x15\n\rexchange_time\x18\x04 \x01(\x03\x12\x0b\n\x03\x62id\x18\x05 \x01(\x03\x12\x0f\n\x07\x62id_qty\x18\x06 \x01(\x03\x12\x0b\n\x03\x61sk\x18\x07 \x01(\x03\x12\x0f\n\x07\x61sk_qty\x18\x08 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUOTES']._serialized_start=22
  _globals['_QUOTES']._serialized_end=169
# @@protoc_insertion_point(module_scope)
